services:

  minio-localdev:
    build:
      context: ./minio
      dockerfile: Dockerfile
    restart: always
    profiles:
      - "localdev"
    ports:
      - "39000:9000"
      - "39001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 3s
      retries: 20

  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    profiles:
      - "testernet"
    expose:
      - "9000"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 3s
      retries: 20
